Enhancement
microsoft/AzureAutomaticGradingEngine pull request #3
Opened 2021-09-27 03:33 UTC by wongcyrus

One click ARM deployment.
Change to use Azure Table.
Add student registration.
Add Student Registration demo video and registration steps in README.
Update GraderArchitecture.png with Azure Table.

2021-09-27 09:10 UTC, leestott requested changes
AzureAutomaticGradingEngineFunctionApp/StudentRegistrationFunction.cs
                log.LogInformation("Form Submit");
                string project = req.Form["project"];
                string email = req.Form["email"];
                string credentials = req.Form["credentials"];
                log.LogInformation("Student Register: " + email + " Project:" + project);
                if (string.IsNullOrWhiteSpace(project) || string.IsNullOrWhiteSpace(email) || string.IsNullOrWhiteSpace(credentials))
                {
Step 2 access to local variable credentials
Sink
AzureAutomaticGradingEngineFunctionApp/StudentRegistrationFunction.cs
                CloudTable credentialsTable = tblclient.GetTableReference("credentials");
                CloudTable subscriptionTable = tblclient.GetTableReference("subscriptions");

                var credentialObject = Newtonsoft.Json.JsonConvert.DeserializeObject<dynamic>(credentials);
 flows to unsafe deserializer.
                string subscriptionId = credentialObject.subscriptionId;

                TableResult result = await subscriptionTable.ExecuteAsync(TableOperation.Retrieve(project, subscriptionId, new List<string>() { "Email" }));

2021-09-28 15:05 UTC, MaximRouiller commented on azuredeploy.json
> +              "value": "https://github.com/microsoft/AzureAutomaticGradingEngine/raw/master/Prebuilt/AzureAutomaticGradingEngineFunctionApp.zip"
Do we have a `master` branch?

2021-09-28 15:06 UTC, MaximRouiller commented on README.md
>  [![Deploy To Azure](https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/1-CONTRIBUTION-GUIDE/images/deploytoazure.svg?sanitize=true)](https://portal.azure.com/#create/Microsoft.
Do we have a `master` branch?

2021-09-28 15:36 UTC, leestott approved these changes

2021-09-28 15:36 UTC, leestott commented on azuredeploy.json
> +              "value": "https://github.com/microsoft/AzureAutomaticGradingEngine/raw/master/Prebuilt/AzureAutomaticGradingEngineFunctionApp.zip"
good catch.

2021-09-28 15:38 UTC, leestott approved these changes
I will update the web app deployment to main after PR merge

2021-09-28 15:39 UTC, merged